### ISSUE TITLE
Bug? Model load does not work properly

### ISSUE THREAD

**Issue by conrad-stork** [Bayer-Group/xBCF#2]
Hi,

thanks for providing this repository. I would be highly interested to try the model. Following the readme I faced different problems which might be minor ones, but in the end I did not manage to make the model run.

First of all it seems to be difficult to install cddd in parallel to your repository as cddd needs python==3.6.x and your repo needs python==3.7.x as otherwise the dependencies (requirements.txt) cannot be installed. I just installed the cddd with python 3.6.x and use the old libraries for your dependencies and this seems to work. Also the way vice versa is possible: so install your dependencies and remove the critical dependencies of cddd. This throws some warnings, but it seems to be okay.

Anyhow in both setups I am not able to call your test.py script as I get the following error:

```console
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    res = test()
  File "test.py", line 20, in test
    res = run_dict(data_dict)
  File "/.../xBCF/src/xbcf.py", line 92, in run_dict
    mtl_attributor = Attributor(QSAR_PATH)
  File "/.../work/xBCF/src/attributor.py", line 74, in __init__
    self.qsar_mdl = cloudpickle.load(open(qsar_model_path, 'rb'))
_pickle.UnpicklingError: invalid load key, 'v'.
```

[Here](https://github.com/svip-lab/PlanarReconstruction/issues/28) they state it could be a problem with the download. Git tells me that I am up to date so I could imagine that it might be a problem with the upload? But it could also something else.

Would be great if I could get some support with this issue.

Thanks in advance and Best!

**Comment by linlinzhao** [comment]
Hi Conrad,

sorry for the delay. The reason could be that I first stored all model artifacts as git LFS, then for the final push, I deleted all LFS and forgot to store the SVR and linear model as normal git files. 

![image](https://user-images.githubusercontent.com/8736548/218305059-2264e2a5-7a15-401a-b72a-bd0cd53899f0.png)

Model files have been added, please give a try again.

**Comment by conrad-stork** [comment]
Thanks, I will try again!

**Comment by conrad-stork** [comment]
Great it is working now. Thanks!
